=== inp-net/churros/server-manifest.schema.json
{
  "type": "object",
  "properties": {
    "version": {
      "type": "string",
      "pattern": "^(dev|(\\d+\\.\\d+\\.\\d+))$"
    },
    "urls": {
      "type": "object",
      "properties": {
        "auth": {
          "type": "string",
          "format": "uri"
        },
        "api": {
          "type": "string",
          "format": "uri"
        }
      },
      "required": ["auth", "api"],
      "additionalProperties": false
    },
    "oauth": {
      "type": "object",
      "properties": {
        "enabled": {
          "type": "boolean"
        },
        "logoutUrl": {
          "type": "string",
          "format": "uri"
        },
        "authorizeUrl": {
          "type": "string",
          "format": "uri"
        },
        "clientId": {
          "type": "string"
        },
        "tokenUrl": {
          "type": "string",
          "format": "uri"
        },
        "userInfoUrl": {
          "type": "string",
          "format": "uri"
        },
        "scopes": {
          "type": "string"
        }
      },
      "required": ["enabled", "scopes"],
      "additionalProperties": false
    },
    "emails": {
      "type": "object",
      "properties": {
        "support": {
          "type": "string",
          "format": "email"
        },
        "contact": {
          "type": "string",
          "format": "email"
        }
      },
      "additionalProperties": false
    }
  },
  "required": ["version", "urls", "oauth", "emails"],
  "additionalProperties": false,
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== inp-net/churros/server-manifest.example.json
{
  "version": "5.0.1",
  "urls": {
    "api": "https://churros.inpt.fr/graphql",
    "auth": "https://churros.inpt.fr/auth"
  },
  "oauth": {
    "enabled": true,
    "clientId": "y87JANYpibsGhWJorAgYO9AOPU9PtecC7WsZwDNo",
    "authorizeUrl": "https://auth.inpt.fr/application/o/authorize/",
    "tokenUrl": "https://auth.inpt.fr/application/o/token/",
    "logoutUrl": "https://auth.inpt.fr/application/o/churros/end-session/",
    "userInfoUrl": "https://auth.inpt.fr/application/o/userinfo/",
    "scopes": "openid profile email"
  },
  "emails": {
    "contact": "contact@net7.dev",
    "support": "contact@net7.dev"
  }
}
